version: "2"
services:
  vpn:
    build:
      context: .
    environment:
      CONF_FILE: /vpn/vpn.ovpn
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /opt/vpn:/vpn